name: architecture_pattern
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

#flutter pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.0

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Storage
  shared_preferences: ^2.2.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI & Theme
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

  # Notifications
  flutter_local_notifications: 18.0.1
  firebase_core:
  firebase_messaging:
  firebase_crashlytics:
  firebase_auth:
  timezone:

  # Image Picker
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Utils
  package_info_plus: ^5.0.1
  permission_handler:

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
