name: architecture_pattern
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # UI & Theme
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.10

  # Image Picker
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Social Auth
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Utils
  logger: ^2.0.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
